### ISSUE TITLE
Slide to open doesn't work!

### ISSUE THREAD

**Issue by ghost** [gylippus/ionic-drawer#1]
Hallo, Thanks a ton for the Android feel Drawer!! The slide to open feature doesn't work though. Can you please fix the bug.

Thanks in advance!!

**Comment by gylippus** [comment]
Hey @naveenkarippai1 , 

Hopefully you have moved on from this. If you haven't gotten something working yet, I would recommend trying a more advanced repo like: 
https://github.com/vitalyrotari/ionic-ion-drawer or https://github.com/brybott/ionic-ion-drawer
