### ISSUE TITLE
Unable to find drawer controller

### ISSUE THREAD

**Issue by anshulklr** [gylippus/ionic-drawer#2]
Controller 'drawer', required by directive 'menuAndDrawerClose', can't be found!

and 

$rootScope.toggleDrawerRoot is not a function

I'm facing these issues when trying to use your code to get a native sidemenu feeling.

**Comment by gylippus** [comment]
Hi @anshulklr, I also had a version or ionic-drawer.js in the Android merges directory that I did not upload before, but they are there now. This contained two other directives:

```
.directive('menuAndDrawerToggle', ['$rootScope', '$ionicGesture', function($rootScope, $ionicGesture) {
  return {
    controller: '',
    link: function($scope, $element, $attr) {
      $element.bind('click', function(){
          $rootScope.toggleDrawerRoot();
      });
    }
  };
}])

.directive('menuAndDrawerClose', ['$ionicViewService', function($ionicViewService) {
  return {
    restrict: 'AC',
    require: '^drawer',
    link: function($scope, $element, $attr, ctrl) {
      $element.bind('click', function(){
        ctrl.close();
      });
    }
  };
}]);
```

I'd honestly recommend trying one of the more advanced repos for this feature though: https://github.com/vitalyrotari/ionic-ion-drawer or https://github.com/brybott/ionic-ion-drawer

Good luck.
